---
sudo: required
services:
- docker
language: node_js
node_js:
- '0.10'
env:
  global:
  - GH_REF: github.com/chad-autry/alpine-rsync
script:
- docker build -t chadautry/alpine-rsync:latest .
- if [[ ! -z "$TRAVIS_TAG" ]]; then docker tag chadautry/alpine-rsync:latest chadautry/alpine-rsync:$TRAVIS_TAG ; fi
after_success:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push chadautry/alpine-rsync